apiVersion: enterprisekgateway.solo.io/v1alpha1
kind: EnterpriseKgatewayTrafficPolicy
metadata:
  name: ektp-apiproducts-oauth
  namespace: kgateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: api-example-com-root-route
    sectionName: httpbin-v1.0
  entExtAuth:
    authConfigRef:
      name: apiproducts-atv-portalauth
      namespace: kgateway-system
  cors:
    allowCredentials: true
    allowHeaders:
    - "*"
    allowMethods:
    - GET
    - OPTIONS
    allowOrigins:
    - "*"
    # allowOriginRegex:
    # - .*
  entRateLimit:
    global:
      rateLimitConfigRefs:
      - name: apiproducts-dynamic
        namespace: kgateway-system
