apiVersion: portal.solo.io/v1alpha1
kind: ApiDoc
metadata:
  name: pets
  namespace: petstore
  labels:
    product: petstore
spec:
  source:
    kube:
      targetRef:
        name: pets-rest-api
        namespace: petstore
        port: 5000
      path: /swagger.json