apiVersion: extauth.solo.io/v1
kind: AuthConfig
metadata:
  name: apiproducts-apikey-portalauth
  namespace: kgateway-system
spec:
  configs:
    - name: portalAuth
      portalAuth:
        url: http://portal-portal.kgateway-system.svc.cluster.local:8080
        cacheDuration: 10s
        apiKeyHeader: "x-api-key"